services:
  db:
    build:
      context: ./postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=lab1"]
      interval: 5s
      timeout: 5s
      retries: 5

  lab-service1:
    build:
      context: ./lab-service
    container_name: lab-service1
    depends_on:
      db:
        condition: service_healthy

  lab-service2:
    build:
      context: ./lab-service
    container_name: lab-service2
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - lab-service1
      - lab-service2
